@startuml
'https://plantuml.com/sequence-diagram

autonumber

 ->Ui:
Ui --> Clue:getClueName()
Ui --> Investigation : getStages()
Investigation --> Investigation:getStage()
Investigation <-- Ui
Ui --> Investigation:getCurrentSceneType()
Ui --> SceneList:getCurrentSceneType()
Ui --> scene:investigateSuspect(suspectName)
scene --> Suspect:getClues()
Ui --> NoteList:getIndexNote()
NoteList --> Note: getNoteTitle()
Ui --> NoteList:getIndexNote()
NoteList --> Note: getNoteTitle()

Ui --> SuspectList:printSuspects(suspects)
SuspectList --> SuspectList:toString()
Ui --> Scene:printAllSuspectInCurrentScene(scene)
Scene --> Scene: toString()
Ui --> Clue:printSelectedClue(scene)
Clue --> Clue: toString()




@enduml