@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> ":Duke": "/next"
activate ":Duke"
":Duke" -> ":Ui": readUserInput()
activate ":Ui"
":Duke" <-- ":Ui": userInput
deactivate ":Ui"
":Duke" -> ":Parser": getCommandFromUser(userInput)
activate ":Parser"
":Parser" -> ":Command": new Command()
activate ":Command"
":Parser" <-- ":Command": Command
deactivate ":Command"
":Duke" <-- ":Parser": CommandFromUser
deactivate ":Parser"
":Duke" -> ":Command": execute(ui,investigation,sceneList)
activate ":Command"
":Duke" <-- ":Command"
deactivate ":Command"
":Duke" -> ":Command": exit()
activate ":Command"
":Duke" <-- ":Command"
deactivate ":Command"
User <-- ":Duke"
deactivate ":Duke"

@enduml