@startuml
'https://plantuml.com/sequence-diagram

autonumber

":GameNoteFileManager"<-":NoteList": openNoteFromFile()
activate ":GameNoteFileManager"
":GameNoteFileManager" --> ":NoteList"
":GameNoteFileManager"<-":NoteList": forceClearNote()
":GameNoteFileManager" --> ":NoteList"
activate ":NoteList"
":NoteList" -> ":NoteList" :getSize()
":NoteList" -> ":Note":createNote(newNote:Note)
activate ":Note"
":NoteList" -> ":GameNoteFileManager":deleteNote(index:int)
":NoteList" -> ":GameNoteFileManager":deleteAllNotes()
":NoteList" -> ":NoteList": processNote(sceneList


@enduml