@startuml
'https://plantuml.com/sequence-diagram

autonumber
activate ":Parser"

":Parser" -> ":Parser": getCommandFromUser("/next")
":Parser" -> ":NextCommand": new NextCommand()
deactivate ":Parser"
activate ":NextCommand"

":NextCommand" -> "sceneList :SceneList": execute()
activate "sceneList :SceneList"

"sceneList :SceneList" -> "sceneList :SceneList": getSceneType()
"sceneList :SceneList" -> "sceneList :SceneList": updateSceneNumber()
"sceneList :SceneList" -> ":NextCommand": runCurrentScene()
deactivate "sceneList :SceneList"

":NextCommand" -> ":NextCommand": exit()


@enduml