@startuml
'https://plantuml.com/sequence-diagram

autonumber

 -> ":Parser": getCommandFromUser("/next")
activate ":Parser"

":Parser" -> ":NextCommand": new NextCommand()
":NextCommand" -> ":Parser": execute()


@enduml